In [2]:
import cv2 as cv 
import numpy as np
# Capturing of the video in order to study 
cap = cv.VideoCapture("C://Users//Asus//Desktop//main.mp4") 

def draw_flow(img,flow,step=16):
    h,w = img.shape[:2]
    y,x = np.mgrid[step/2:h:step , step/2:w:step].reshape(2,-1).astype(int)
    fx , fy = flow[y,x].T
    lines = np.vstack([x,y,x-fx,y-fy]).T.reshape(-1,2,2)
    lines = np.int32(lines+0.5)
    img_bgr = cv.cvtColor(img,cv2.COLOR_GRAY2BGR)
    cv.polylines(img_bgr,lines,0,(0,255,0))
    
    for(x1,y1), (_x2,_y2) in lines :
        cv.circle(img_bgr,(x1,y1),1,(0,255,0),-1)
        
    return img_bgr

def draw_hsv(flow):
    h,w = flow.shape[:2]
    fx , fy = flow[:,:,0],flow[:,:,1]
    
    ang = np.arctan2(fy,fx) + np.pi
    v= np.sqrt(fx*fx+fy*fy)
    
    hsv = np.zeros((h,w,3),np.uint8)
    hsv[...,0] = ang*(180/np.pi/2)
    hsv[...,1] = 255
    hsv[...,2] = np.minimum(v*4,255)
    bgr = cv.cvtColor(hsv, cv.COLOR_HSV2BGR)
    return bgr


# ret = a boolean return value from 
# getting the frame, first_frame = the 
# first frame in the entire video sequence 

ret, first_frame = cap.read() 
#print(ret,"----> " , first_frame)

# Converts frame to grayscale because we 
# only need the luminance channel for 
# detecting edges - less computationally  
# expensive 

prev_gray = cv.cvtColor(first_frame, cv.COLOR_BGR2GRAY) 
  
# Creates an image filled with zero 
# intensities with the same dimensions  
# as the frame 

mask = np.zeros_like(first_frame) 

  
# Sets image saturation to maximum 

mask[..., 1] = 255



while(cap.isOpened()): 

    # ret = a boolean return value from getting 
    # the frame, frame = the current frame being 
    # projected in the video 
    ret, frame = cap.read() 

    # Opens a new window and displays the input 
    # frame 
    cv.imshow("input", frame) 

    # Converts each frame to grayscale - we previously  
    # only converted the first frame to grayscale 
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY) 

    # Calculates dense optical flow by Farneback method 
    flow = cv.calcOpticalFlowFarneback(prev_gray, gray, None, 0.5, 3, 15, 3, 5, 1.2, 0) 

    # Computes the magnitude and angle of the 2D vectors
    magnitude, angle = cv.cartToPolar(flow[..., 0], flow[..., 1]) 

    # Sets image hue according to the optical flow  
    # direction 
    mask[..., 0] = angle * 180 / np.pi / 2

    # Sets image value according to the optical flow 
    # magnitude (normalized) 
    mask[..., 2] = cv.normalize(magnitude, None, 0, 255, cv.NORM_MINMAX) 

    # Converts HSV to RGB (BGR) color representation 
    rgb = cv.cvtColor(mask, cv.COLOR_HSV2BGR) 

      

    # Opens a new window and displays the output frame 
    cv.imshow("dense optical flow" ,flow , draw_flow(gray,flow), rgb) 

    # Updates previous frame 
    prev_gray = gray 

    # Frames are read by intervals of 1 millisecond. The 
    # programs breaks out of the while loop when the 
    # user presses the 'q' key 
    if cv.waitKey(1) & 0xFF == ord('q'): 
        break

  
# The following frees up resources and 
# closes all windows 
cap.release() 
cv.destroyAllWindows()  

error: OpenCV(4.5.4-dev) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - imshow() takes at most 2 arguments (4 given)
>  - imshow() takes at most 2 arguments (4 given)
>  - imshow() takes at most 2 arguments (4 given)


In [2]:
import numpy as np
import cv2
import time
from PIL import Image


def draw_flow(img, flow, step=16):
    
    #will give the shape of the image
    h, w = img.shape[:2]
    
    
    y, x = np.mgrid[step/2:h:step, step/2:w:step].reshape(2,-1).astype(int)
    fx, fy = flow[y,x].T

    lines = np.vstack([x, y, x-fx, y-fy]).T.reshape(-1, 2, 2)
    lines = np.int32(lines + 0.5)

    img_bgr = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR)
    cv2.polylines(img_bgr, lines, 0, (0, 255, 0))

    for (x1, y1), (_x2, _y2) in lines:
        cv2.circle(img_bgr, (x1, y1), 1, (0, 255, 0), -1)

    return img_bgr


def draw_hsv(flow):

    h, w = flow.shape[:2]
    fx, fy = flow[:,:,0], flow[:,:,1]

    ang = np.arctan2(fy, fx) + np.pi
    v = np.sqrt(fx*fx+fy*fy)

    hsv = np.zeros((h, w, 3), np.uint8)
    hsv[...,0] = ang*(180/np.pi/2)
    hsv[...,1] = 255
    hsv[...,2] = np.minimum(v*4, 255)
    bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

    return bgr




cap = cv2.VideoCapture("C://Users//Asus//Desktop//main.mp4")
#cap = cv2.VideoCapture(0)

#will give us the image in numkber format
suc, prev = cap.read()
#print(prev)

model_frame = []
#y axix
for i in range(1080):
    temp = []
    for j in range(1920):
        temp.append([0,0,0])
    model_frame.append(temp)
model_frame=np.array(model_frame)

img = Image. fromarray(model_frame, 'RGB')
img.save('my.png')
    
#will convert to greyscale
prevgray = cv2.cvtColor(prev, cv2.COLOR_BGR2GRAY)

while True:
    #reading of image until its true
    suc, img = cap.read()
    print(img)
    print(len(img))
    
    count_x = 0
    
    
    """for i in range img :
        count_y = 0
        for j in i :
            count = 0
            k = j
            while count!=12 : 
                k = np.append(k,[0,0,0])
                count = count + 1
            img[count_x][count_y] = k
            count_y = count_y + 1
        count_x = count_x + 1"""

    
    #converstion to grey scale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # start time to calculate FPS
    start = time.time()
    
    

    #calculation of optical flow
    flow = cv2.calcOpticalFlowFarneback(prevgray # previous frame
                                        , gray # next frame 
                                        , None 
                                        , 0.5
                                        , 3
                                        , 15
                                        , 3
                                        , 5
                                        , 1.2
                                        , 0)
    
    end = time.time()
    print("************************************")
    print(flow)
    img.resize(1092,1932,3)
    
    # calculate the FPS for current frame detection
    fps = 1 / (end-start)
    
    n_i = 0
    print("*************************************************************///////////////////////")
    
    for i in range(len(img)-12) :
        for j in range(len(img[i])-12) :
            temp_i = int(i+3*2*flow[i][j][0])
            temp_j = int(j+3*2*flow[i][j][1])
            if (temp_j>=1920 or temp_i>=1080):
                continue
                
            model_frame[temp_i][temp_j] = img[i][j]
    
            
    
    
    
    data = Image.fromarray(model_frame,"RGB")
    data.save('gfg_dummy_pic.png')
    
    prevgray = gray
    
    #1080
    #1920


    # End time
   
    
    
    
    print(f"{fps:.2f} FPS")

    cv2.imshow('flow', draw_flow(gray, flow))
    cv2.imshow('flow HSV', draw_hsv(flow))


    key = cv2.waitKey(5)
    if key == ord('q'):
        break


cap.release()
cv2.destroyAllWindows()

[[[ 6 10 12]
  [ 6 10 12]
  [ 6 10 12]
  ...
  [33 33 33]
  [34 34 34]
  [34 34 34]]

 [[ 6 10 12]
  [ 6 10 12]
  [ 6 10 12]
  ...
  [36 36 36]
  [36 36 36]
  [37 37 37]]

 [[ 6 10 12]
  [ 6 10 12]
  [ 6 10 12]
  ...
  [33 33 33]
  [33 33 33]
  [36 36 36]]

 ...

 [[45 45 45]
  [45 45 45]
  [45 45 45]
  ...
  [33 33 33]
  [33 33 33]
  [33 33 33]]

 [[44 44 44]
  [44 44 44]
  [44 44 44]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]

 [[43 43 43]
  [43 43 43]
  [43 43 43]
  ...
  [32 32 32]
  [32 32 32]
  [32 32 32]]]
1080
************************************
[[[ 3.83874075e-03 -5.18030440e-03]
  [ 1.04344962e-02 -1.21283066e-02]
  [ 1.59380008e-02 -2.15685014e-02]
  ...
  [ 6.51352927e-02 -7.10958987e-02]
  [ 4.80417162e-02 -4.96102720e-02]
  [ 3.25380489e-02 -3.17878090e-02]]

 [[ 8.11993238e-03 -8.10846873e-03]
  [ 2.05958262e-02 -1.92833655e-02]
  [ 2.94259675e-02 -3.35073620e-02]
  ...
  [ 8.87432098e-02 -1.08259425e-01]
  [ 6.85704574e-02 -7.83817545e-02]
  [ 5.01265898e-02 -5.4529

In [6]:
import numpy as np
import cv2 as cv
import argparse
parser = argparse.ArgumentParser(description='This sample demonstrates Lucas-Kanade Optical Flow calculation. \
                                              The example file can be downloaded from: \
                                              https://www.bogotobogo.com/python/OpenCV_Python/images/mean_shift_tracking/slow_traffic_small.mp4')
parser.add_argument('image', type=str, help='path to image file')
args = parser.parse_args()
cap = cv.VideoCapture(args.image)
# params for ShiTomasi corner detection
feature_params = dict( maxCorners = 100,
                       qualityLevel = 0.3,
                       minDistance = 7,
                       blockSize = 7 )
# Parameters for lucas kanade optical flow
lk_params = dict( winSize  = (15, 15),
                  maxLevel = 2,
                  criteria = (cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 0.03))
# Create some random colors
color = np.random.randint(0, 255, (100, 3))
# Take first frame and find corners in it
ret, old_frame = cap.read()
old_gray = cv.cvtColor(old_frame, cv.COLOR_BGR2GRAY)
p0 = cv.goodFeaturesToTrack(old_gray, mask = None, **feature_params)
# Create a mask image for drawing purposes
mask = np.zeros_like(old_frame)
while(1):
    ret, frame = cap.read()
    if not ret:
        print('No frames grabbed!')
        break
    frame_gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # calculate optical flow
    p1, st, err = cv.calcOpticalFlowPyrLK(old_gray, frame_gray, p0, None, **lk_params)
    # Select good points
    if p1 is not None:
        good_new = p1[st==1]
        good_old = p0[st==1]
    # draw the tracks
    for i, (new, old) in enumerate(zip(good_new, good_old)):
        a, b = new.ravel()
        c, d = old.ravel()
        mask = cv.line(mask, (int(a), int(b)), (int(c), int(d)), color[i].tolist(), 2)
        frame = cv.circle(frame, (int(a), int(b)), 5, color[i].tolist(), -1)
    img = cv.add(frame, mask)
    cv.imshow('frame', img)
    k = cv.waitKey(30) & 0xff
    if k == 27:
        break
    # Now update the previous frame and previous points
    old_gray = frame_gray.copy()
    p0 = good_new.reshape(-1, 1, 2)
cv.destroyAllWindows()

usage: ipykernel_launcher.py [-h] image
ipykernel_launcher.py: error: unrecognized arguments: -f


SystemExit: 2

C:\Users\Asus\anaconda3\envs\Internship\lib\site-packages\IPython\core\interactiveshell.py:3452: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
